@token=

### 기사님 회원가입(local)
POST http://localhost:4000/auth/signup/mover
Content-Type: application/json

{
    "name": "t6",
     "email": "test6@test.com", 
     "phone": "01066666666", 
     "password": "a66666666",
       "passwordConfirmation":"a66666666"
}

###기사님 로그인(local)
POST http://localhost:4000/auth/signin/mover
Content-Type: application/json

{
     "email": "test5@test.com", 
     "password": "a5555555"
}

### 일반 회원 회원가입(local)
POST http://localhost:4000/auth/signup/client
Content-Type: application/json

{
     "name": "일반인",
     "email": "test5@test.com", 
     "phone": "03112345679", 
     "password": "asdf1234",
     "passwordConfirmation": "asdf1234"
}

### 일반 회원 로그인(local)
POST http://localhost:4000/auth/signin/client
Content-Type: application/json

{
     "email": "0sky@example.com", 
     "password": "asdf1234"
}

### RefreshToken
POST http://localhost:4000/auth/refresh-token
Content-Type: application/json
Cookie: refreshToken=값

### 사용자 불러오기
GET http://localhost:4000/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjMjVhMzk0Mi01MzYzLTRkMDYtOGYzYS01MjY1NzY3NDE4YzQiLCJlbWFpbCI6IjBza3lAZXhhbXBsZS5jb20iLCJuYW1lIjoi7JaR7ISx6rK9IiwidXNlclR5cGUiOiJjbGllbnQiLCJpYXQiOjE3NTI1MDQ2NDEsImV4cCI6MTc1MjUwODI0MX0.jFsM0pGbg1cn_DZX5Fgnj26f6Sxw2JDRlsMfCkeT4uU