@token=

### 기사님 회원가입
POST http://localhost:4000/auth/signup/mover
Content-Type: application/json

{
    "name": "tester3",
     "email": "test3@test.com", 
     "phone": "01033333333", 
     "password": "3333"
}

###기사님 로그인
POST http://localhost:4000/auth/signin/mover
Content-Type: application/json

{
     "email": "test2@test.com", 
     "password": "2222"
}

### 일반 회원 회원가입(local)
POST http://localhost:4000/auth/signup/client
Content-Type: application/json

{
     "name": "일반인",
     "email": "test4@test.com", 
     "phoneNumber": "03112345678", 
     "password": "asdf1234",
     "passwordConfirmation": "asdf1234"
}

### 일반 회원 로그인(local)
POST http://localhost:4000/auth/signin/client
Content-Type: application/json

{
     "email": "test4@test.com", 
     "password": "asdf1234"
}

### RefreshToken
POST http://localhost:4000/auth/refresh-token
Content-Type: application/json
Cookie: refreshToken=값

### 사용자 불러오기
GET http://localhost:4000/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmRkNTY2OC02Nzg3LTQ1MTktYjliMS0zN2Y4OGMyY2QxN2UiLCJlbWFpbCI6InRlc3Q0QHRlc3QuY29tIiwibmFtZSI6IuydvOuwmOyduCIsInVzZXJUeXBlIjoiY2xpZW50IiwiaWF0IjoxNzUyMjA4NzUxLCJleHAiOjE3NTIyMTIzNTF9.rGiRN1zS-MiUs9O5RwX9fMkpaoBV_pBQHgmN8pDj_78