@token=

### 대기 중인 견적 조회
GET http://localhost:4000/estimates/pending
Content-Type: application/json
Authorization: Bearer {{token}}

### 작성 가능한 리뷰 견적 목록 조회 (페이지네이션)
GET http://localhost:4000/estimates/writable/me?page=1&pageSize=6
Authorization: Bearer {{token}}
Accept: application/json

### 작성 가능한 리뷰 견적 목록 조회 (모바일/태블릿, 4개씩)
GET http://localhost:4000/estimates/writable/me?page=1&pageSize=4
Authorization: Bearer {{token}}
Accept: application/json

### 작성 가능한 리뷰 견적 목록 조회 (2페이지, 6개씩)
GET http://localhost:4000/estimates/writable/me?page=2&pageSize=6
Authorization: Bearer {{token}}
Accept: application/json

### 받은 견적 조회
GET http://localhost:4000/estimates/received
Content-Type: application/json
Authorization: Bearer {{token}}

### 견적 요청 (기사 → 고객에게)
POST http://localhost:4000/estimates/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "price": 150000,
  "comment": "안녕하세요, 빠르고 안전하게 도와드리겠습니다.",
  "clientId": "클라이언트_ID",
  "requestId": "요청_ID"
}

### 견적 거절 (기사 → 고객 견적 거절)
POST http://localhost:4000/estimates/reject
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "comment": "죄송합니다. 일정이 맞지 않습니다.",
  "clientId": "클라이언트_ID",
  "requestId": "요청_ID"
}

### 견적 확정 테스트
POST http://localhost:4000/estimates/confirmed
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "estimateId": "ddc7beb4-f645-4e12-8749-14aac1a688ab"
}