@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyOTZhNmFjOC0yYjY3LTQ1ZTYtOWJlNi1kYTA1MzE5MjE1ZTUiLCJlbWFpbCI6InNreTEzQHRlc3QuY29tIiwibmFtZSI6IuydvOuwmOyduCIsInVzZXJUeXBlIjoiY2xpZW50IiwiaWF0IjoxNzUzNjMwMzQ5LCJleHAiOjE3NTM2MzM5NDl9.DmGYDU2QQQoMFtz1TuJbiEUrw_0OL1yyxGrHxBQccww
@moverToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNjZkNTZkYS03YTE0LTRlMjgtYjRjMC1mZmNlZTdiYWJhMjkiLCJlbWFpbCI6Im1vdmVyMUBnbWFpbC5jb20iLCJuYW1lIjoi7LKg6rCA67CpIOyalOumrOyCrCIsInVzZXJUeXBlIjoibW92ZXIiLCJpYXQiOjE3NTM2MzExNzksImV4cCI6MTc1MzYzNDc3OX0.YGZ1zpqXgjGgvE2R0mc-7ijJ1USJp2iygigHhhKTUZ0
@moverId=b66d56da-7a14-4e28-b4c0-ffcee7baba29
### 전체 기사님 리스트 조회 (비회원도 가능)
GET http://localhost:4000/movers

### 기사님 상세 조회 (비회원도 가능)
GET http://localhost:4000/movers/{{moverId}}

### 기사님 찜 토글
# 현재 찜 상태에 따라 자동으로 추가/해제
POST http://localhost:4000/movers/{{moverId}}/toggle-favorite
Authorization: Bearer {{token}}
Content-Type: application/json

{}

### 기사님 본인의 프로필 조회
GET http://localhost:4000/movers/profile
Host: localhost:4000
Authorization: Bearer {{moverToken}}
Content-Type: application/json

### 기사님 지정 요청 (견적서와 매칭)
PATCH http://localhost:4000/movers/d9da38fd-0b93-4fd9-9449-f4d29d1c864a
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "requestId": "721a2ea4-56e2-4504-a0d6-5a7c0158e5c7",
  "moverId": "d9da38fd-0b93-4fd9-9449-f4d29d1c864a"
}

