@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhN2JmMjk3Ny05ZDE2LTQwOTctODRiZC03MzkzNDQxNWRlNWUiLCJlbWFpbCI6InNreUBleGFtcGxlLmNvbSIsIm5hbWUiOiJza3kiLCJ1c2VyVHlwZSI6ImNsaWVudCIsImlhdCI6MTc1MzA4NTI3MCwiZXhwIjoxNzUzMDg4ODcwfQ.71YsCRvgiC2giYxrK6y27xTHLZGg26MwlHphZNFqWf8

GET http://localhost:4000/notifications
Authorization: Bearer {{token}}