@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ZDExNzRjZi0xMDViLTRhNTctYWE3NC03YTk1NTViMmFkZDgiLCJlbWFpbCI6InNreTNAZXhhbXBsZS5jb20iLCJuYW1lIjoic2t5IiwidXNlclR5cGUiOiJjbGllbnQiLCJpYXQiOjE3NTMzNTExOTcsImV4cCI6MTc1MzM1NDc5N30.ze6qY6xdy9xn74mSCwmnK2Cj7Zht4DdwVmHbP2H4WDo

# ### 기사님 프로필 등록
# POST http://localhost:4000/profile/mover
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#      "nickName": "무빙7", 
#      "career": 7, 
#      "introduction":"안녕하세요 ㅂㅁ7입니다",  
#      "description":"안녕하세요 ㅂㅁ7입니다" , 
#      "serviceType":["소형이사"],
#      "serviceArea": ["서울", "경기"]
# }

### 기사님 프로필 생성 & 수정
PATCH  http://localhost:4000/profile/mover
Content-Type: application/json
Authorization: Bearer {{token}}

{
     "nickName": "무빙7-1", 
     "career": 6, 
     "introduction":"안녕하세요 ㅂㅁ7입니다",  
     "description":"안녕하세요 ㅂㅁ7입니다" , 
     "serviceType":["사무실이사"],
     "serviceArea": ["충남", "인천"]
}

### 일반 프로필 등록
PATCH http://localhost:4000/profile/clients
Content-Type: application/json
Authorization: Bearer {{token}}

{
     "serviceType": ["SMALL", "HOME"],
     "livingArea": ["서울", "경기"]
}

### 일반 프로필 수정
PATCH http://localhost:4000/profile/clients
Content-Type: application/json
Authorization: Bearer {{token}}

{
     "serviceType": ["SMALL", "HOME"],
     "livingArea": ["서울", "경기"]
}