@client_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiYTI1YTYzOC04M2FhLTQ0ZjEtYjI1OC03MmIyMTAxZjBlZDgiLCJlbWFpbCI6ImNsaWVudDFAZXhhbXBsZS5jb20iLCJuYW1lIjoi6rOg6rCdMSIsInVzZXJUeXBlIjoiY2xpZW50IiwiaWF0IjoxNzUyNDgwMjc1LCJleHAiOjE3NTI0ODM4NzV9.RxWiUgcUm9d2OUxFSTF_TTGx6lLnc0GmtMNVOAG72sE
@mover_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyODdlOTRlOS1jODQ2LTQ5NjMtOTY0NS1kNmQzM2JkNWYzYWUiLCJlbWFpbCI6Im1vdmVyMUBleGFtcGxlLmNvbSIsIm5hbWUiOiLquLDsgqwxIiwidXNlclR5cGUiOiJtb3ZlciIsImlhdCI6MTc1MjQ4MDM2NCwiZXhwIjoxNzUyNDgzOTY0fQ.57sRLh0dPmy3qZ7umy4FuoYwoKY-WP_rVcwRZQHL46c

### 견적 요청 (일반 유저)
POST http://localhost:4000/requests
Content-Type: application/json
Authorization: Bearer {{client_token}}

{
  "moveType": "SMALL",
  "moveDate": "2025-07-09T00:00:00.000Z",
  "fromAddress": "대전 서구 가수원로 17-19",
  "toAddress": "부산 해운대구 구남로 5"
}

### 받은 요청 조회 (기사님) - 기본 6개 + 커서
GET http://localhost:4000/requests?cursor=acf0f087-cf9a-46dc-82aa-9a412a6b4980
Authorization: Bearer {{mover_token}}

### 받은 요청 조회 (기사님) - 이사 유형 필터
GET http://localhost:4000/requests?moveType=OFFICE,SMALL
Authorization: Bearer {{mover_token}}

### 받은 요청 조회 (기사님) - 서비스 가능 지역 필터
GET http://localhost:4000/requests?serviceArea=대전,서울
Authorization: Bearer {{mover_token}}

### 받은 요청 조회 (기사님) - 지정 견적 필터
GET http://localhost:4000/requests?isDesignated=true
Authorization: Bearer {{mover_token}}

### 받은 요청 조회 (기사님) - 검색 & 정렬
GET http://localhost:4000/requests?&sort=requestedAt&keyword=고객1
Authorization: Bearer {{mover_token}}